# Site settings
# Update all variables under site settings.
title: NIST Microstructure Project # Update the name of your project
header-img: img/home-bg.jpg # Add a photo related to your project
email: ajmedfor@gmail.com #Update your email address
description: "Applying materials informatics to understand microstructure." # Update description of your project
baseurl: "/nist-microstructure" # Update to "/<name of your repository>"
url: "http://ajmedford.github.io" # Update to "http://<github username>.github.io"
github_username:  ajmedford # Update to your <github_username>
project_repository: nist-microstructure # Update to your <repository name>

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
